on: push
name: Deploy
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
  release:
    name: Make release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare files
        shell: bash
        run: |
          mkdir dist
          cd dist
          cp ../target/release/rust-deploy-test* .
          #cp -r ../assets .
          ls
      - name: Release
        if: false
        uses: softprops/action-gh-release@v1
